### PR TITLE
ACL: Add tests

### PR DESCRIPTION
**Pull request by palash25**
Related to: https://github.com/gojektech/weaver/issues/20

cc @rShetty

### CODE REVIEW

**Comment by rShetty** [comment]
@palash25 Checks are failing

**Comment by palash25** [comment]
@rShetty the following echo command is failing

`$ echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
Must provide --username with --password-stdin
The command "echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin" failed and exited with 1 during .`

I am not really sure how it is related to my test, it was passing locally.

I tried a rebuild but I am getting the same failure.

Any ideas on how to fix that?

**Comment by gwthm-in** [comment]
@palash25 fixed it in this 59995fef1e88dbb087980236bd2f7b0e60bdc6a7 commit.

**Comment by palash25** [comment]
thanks @gowtham-sai repushed. Tests are passing now :smile:

**Comment by rShetty** [comment]
@palash25 You might want to add more tests

**Comment by palash25** [comment]
@rShetty I will push a few more test cases in the coming days

**Pull request merged**
