### PR TITLE
fix import paths

### PR DESCRIPTION
**Pull request by darshanime**
currently it references `gojektech` in multiple places

### CODE REVIEW

**Comment by spy16** [comment]
Go module path is `github.com/gojektech/weaver` since eventually this will move there.

**Comment by darshanime** [comment]
shouldn't this be changed back to `gojektech` once it is actually migrated? 🤔  
currently, `weaver` can't be getted, compiled, tested locally.

**Comment by spy16** [comment]
Since it uses `go mod` support, you should be able to build and run without issues (provided you have go 1.11.1 and above)..  You should either set `GO111MODULE=on` if you are cloning inside `GOPATH` or simply run `make build` if you are cloning anywhere outside of `GOPATH`

**Comment by darshanime** [comment]
oh okies. I am still on `1.10.7`. closing.

**Pull request closed without merging**
